auto:        false
server:      false

source:      .
destination: ./_site

paginate:    4

permalink:   /away/:year/:month/:day/:title
# Configuration option that only takes effect in special version of pagination.
# Represents the subdirectory that all content will be placed under.
# In the case of pagination, it should create content at away/page2, etc.
subdir:      away/

exclude:     README, _posts/2001-12-30-template.markdown
